bot-token: "YOUR DISCORD BOT TOKEN HERE"
channel-id: "1234567890"

discord-to-minecraft-message-format: "<ยง9%discord-nickname%ยงf> %discord-message%"
minecraft-to-discord-message-format: "<%minecraft-nickname%> %minecraft-message%"